GET http://localhost:8008/api/account?email=test&password=test
Accept: application/json

###
POST http://localhost:8008/api/account
Content-Type: application/json

{
  "fName": "test",
  "lName": "Test",
  "email": "test",
  "password": "test",
  "bDate": 1234
}

###
